"""Shared utility package exports."""

from .config_helpers import (
    cfg_default,
    resolve_method_optim_field,
    resolve_workflow_dataset_cfg,
    tag_if_nondefault,
    validate_choice,
    validate_probability,
)
from .dataset_helpers import (
    canonical_source_dataset_name,
    checkpoint_dataset_dir_name,
    is_few_shot_split,
    normalize_node_mask,
    populate_dataset_cfg_from_meta,
    read_effective_task_level,
    resolve_effective_task_level,
    resolve_loader_task_level,
    resolve_split_task_level,
    shared_induced_root,
    shared_split_root,
    split_dataset_name,
)
from .io import append_csv_row, parse_csv_list, read_name_list_file
from .metrics import compute_supervised_metrics
from .naming import (
    build_pretrain_run_name_from_cfg,
    compact_artifact_stem,
    format_split_for_name,
    model_variant_tag_for,
)
from .paths import (
    PROJECT_ROOT,
    ensure_dir,
    ensure_project_root_on_path,
    project_path,
    project_root,
    resolve_project_path,
)
from .parsing import (
    has_valid_config_file,
    looks_bool,
    looks_int,
    looks_split_literal,
    parse_bool,
    parse_fixed_split,
    resolve_task_type,
    to_bool,
    validate_required_dataset_overrides,
)
from .pool import (
    POOLERS,
    get_batch_vector,
    get_pool_fn,
    normalize_pool_mode,
    pool_nodes,
    resolve_graph_repr,
)
from .random import set_seed
from .supervised_eval import evaluate_epoch_split, evaluate_supervised_split
from .supervised_forward import select_supervised_logits_and_labels
from .training import build_lr_scheduler, run_epoch_loop, run_step_epoch
from .checkpoint import (
    cfg_to_dict,
    save_checkpoint,
    save_json_atomic,
    save_torch_atomic,
    save_training_log,
)
from .supervised_loss import (
    binary_targets_and_valid,
    prepare_class_labels,
    resolve_supervised_output_dim,
    supervised_loss_from_logits,
)

__all__ = [
    "PROJECT_ROOT",
    "cfg_default",
    "resolve_method_optim_field",
    "resolve_workflow_dataset_cfg",
    "tag_if_nondefault",
    "validate_choice",
    "validate_probability",
    "canonical_source_dataset_name",
    "checkpoint_dataset_dir_name",
    "is_few_shot_split",
    "populate_dataset_cfg_from_meta",
    "read_effective_task_level",
    "resolve_effective_task_level",
    "resolve_loader_task_level",
    "resolve_split_task_level",
    "shared_induced_root",
    "shared_split_root",
    "split_dataset_name",
    "append_csv_row",
    "build_pretrain_run_name_from_cfg",
    "compact_artifact_stem",
    "compute_supervised_metrics",
    "ensure_dir",
    "ensure_project_root_on_path",
    "format_split_for_name",
    "model_variant_tag_for",
    "has_valid_config_file",
    "looks_bool",
    "looks_int",
    "looks_split_literal",
    "parse_bool",
    "parse_csv_list",
    "parse_fixed_split",
    "POOLERS",
    "get_batch_vector",
    "get_pool_fn",
    "normalize_pool_mode",
    "pool_nodes",
    "resolve_graph_repr",
    "project_path",
    "project_root",
    "read_name_list_file",
    "resolve_project_path",
    "set_seed",
    "to_bool",
    "validate_required_dataset_overrides",
    "build_lr_scheduler",
    "run_epoch_loop",
    "run_step_epoch",
    "normalize_node_mask",
    "binary_targets_and_valid",
    "prepare_class_labels",
    "resolve_supervised_output_dim",
    "evaluate_epoch_split",
    "evaluate_supervised_split",
    "select_supervised_logits_and_labels",
    "supervised_loss_from_logits",
    "cfg_to_dict",
    "save_checkpoint",
    "save_json_atomic",
    "save_torch_atomic",
    "save_training_log",
]
